# Generated by Django 3.1.7 on 2021-03-11 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Speakers',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(default='', upload_to='home/images')),
                ('status', models.CharField(max_length=200)),
                ('bio', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
