# Generated by Django 3.1.7 on 2021-03-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20210311_1411'),
    ]

    operations = [
        migrations.CreateModel(
            name='UpcomingEvents',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('speaker', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
    ]
