# Generated by Django 3.1.7 on 2021-05-26 03:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_upcomingevents'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Faq',
        ),
        migrations.DeleteModel(
            name='Speakers',
        ),
    ]
