# Generated by Django 3.1.7 on 2021-06-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_postevents'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreEvent',
            fields=[
                ('sno', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('is_approved', models.BooleanField(default=False)),
                ('speaker', models.CharField(max_length=50)),
                ('slug', models.CharField(max_length=200)),
                ('timeStamp', models.DateTimeField(blank=True)),
                ('content', models.TextField()),
            ],
            options={
                'ordering': ['-timeStamp'],
            },
        ),
        migrations.RenameModel(
            old_name='Post',
            new_name='Blog',
        ),
        migrations.RenameModel(
            old_name='PostEvents',
            new_name='PostEvent',
        ),
        migrations.DeleteModel(
            name='UpcomingEvents',
        ),
    ]
